//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orc.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orc.Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for file.
        /// </summary>
        internal static string Controls_BrowseForFile {
            get {
                return ResourceManager.GetString("Controls_BrowseForFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for folder.
        /// </summary>
        internal static string Controls_BrowseForFolder {
            get {
                return ResourceManager.GetString("Controls_BrowseForFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string Controls_DateRangePicker_Custom {
            get {
                return ResourceManager.GetString("Controls_DateRangePicker_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End:.
        /// </summary>
        internal static string Controls_DateRangePicker_End_Lbl {
            get {
                return ResourceManager.GetString("Controls_DateRangePicker_End_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last month.
        /// </summary>
        internal static string Controls_DateRangePicker_LastMonth {
            get {
                return ResourceManager.GetString("Controls_DateRangePicker_LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last week.
        /// </summary>
        internal static string Controls_DateRangePicker_LastWeek {
            get {
                return ResourceManager.GetString("Controls_DateRangePicker_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start:.
        /// </summary>
        internal static string Controls_DateRangePicker_Start_Lbl {
            get {
                return ResourceManager.GetString("Controls_DateRangePicker_Start_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This month.
        /// </summary>
        internal static string Controls_DateRangePicker_ThisMonth {
            get {
                return ResourceManager.GetString("Controls_DateRangePicker_ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This week.
        /// </summary>
        internal static string Controls_DateRangePicker_ThisWeek {
            get {
                return ResourceManager.GetString("Controls_DateRangePicker_ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Controls_DateRangePicker_Today {
            get {
                return ResourceManager.GetString("Controls_DateRangePicker_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string Controls_DateRangePicker_Yesterday {
            get {
                return ResourceManager.GetString("Controls_DateRangePicker_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        internal static string Controls_OpenFolder {
            get {
                return ResourceManager.GetString("Controls_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all.
        /// </summary>
        internal static string Controls_ValidationContextControl_CollapseAll {
            get {
                return ResourceManager.GetString("Controls_ValidationContextControl_CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Controls_ValidationContextControl_Copy {
            get {
                return ResourceManager.GetString("Controls_ValidationContextControl_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        internal static string Controls_ValidationContextControl_Errors {
            get {
                return ResourceManager.GetString("Controls_ValidationContextControl_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all.
        /// </summary>
        internal static string Controls_ValidationContextControl_ExpandAll {
            get {
                return ResourceManager.GetString("Controls_ValidationContextControl_ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Controls_ValidationContextControl_Filter {
            get {
                return ResourceManager.GetString("Controls_ValidationContextControl_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        internal static string Controls_ValidationContextControl_Misc {
            get {
                return ResourceManager.GetString("Controls_ValidationContextControl_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Controls_ValidationContextControl_Open {
            get {
                return ResourceManager.GetString("Controls_ValidationContextControl_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        internal static string Controls_ValidationContextControl_Warnings {
            get {
                return ResourceManager.GetString("Controls_ValidationContextControl_Warnings", resourceCulture);
            }
        }
    }
}
