//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orc.Automation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orc.Automation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for file.
        /// </summary>
        internal static string Controls_BrowseForFile {
            get {
                return ResourceManager.GetString("Controls_BrowseForFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for folder.
        /// </summary>
        internal static string Controls_BrowseForFolder {
            get {
                return ResourceManager.GetString("Controls_BrowseForFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Controls_Clear {
            get {
                return ResourceManager.GetString("Controls_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear selection.
        /// </summary>
        internal static string Controls_ColorLegendGeneric_Button_Content_ClearSelection {
            get {
                return ResourceManager.GetString("Controls_ColorLegendGeneric_Button_Content_ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Color Edit.
        /// </summary>
        internal static string Controls_ColorLegendGeneric_CheckBox_Content_AllowColorEdit {
            get {
                return ResourceManager.GetString("Controls_ColorLegendGeneric_CheckBox_Content_AllowColorEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check all.
        /// </summary>
        internal static string Controls_ColorLegendGeneric_CheckBox_Content_CheckAll {
            get {
                return ResourceManager.GetString("Controls_ColorLegendGeneric_CheckBox_Content_CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Visibility Column.
        /// </summary>
        internal static string Controls_ColorLegendGeneric_CheckBox_Content_ShowVisibilityColumn {
            get {
                return ResourceManager.GetString("Controls_ColorLegendGeneric_CheckBox_Content_ShowVisibilityColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Controls_ColorPickerGeneric_Button_Content_Cancel {
            get {
                return ResourceManager.GetString("Controls_ColorPickerGeneric_Button_Content_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Controls_ColorPickerGeneric_Button_Content_Select {
            get {
                return ResourceManager.GetString("Controls_ColorPickerGeneric_Button_Content_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        internal static string Controls_ColorPickerGeneric_TabItem_Header_Colors {
            get {
                return ResourceManager.GetString("Controls_ColorPickerGeneric_TabItem_Header_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSV.
        /// </summary>
        internal static string Controls_ColorPickerGeneric_TabItem_Header_HSV {
            get {
                return ResourceManager.GetString("Controls_ColorPickerGeneric_TabItem_Header_HSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent colors.
        /// </summary>
        internal static string Controls_ColorPickerGeneric_TextBlock_Text_RecentColors {
            get {
                return ResourceManager.GetString("Controls_ColorPickerGeneric_TextBlock_Text_RecentColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme colors.
        /// </summary>
        internal static string Controls_ColorPickerGeneric_TextBlock_Text_ThemeColors {
            get {
                return ResourceManager.GetString("Controls_ColorPickerGeneric_TextBlock_Text_ThemeColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string Controls_ConnectionStringAdvancedOptionsWindow_DataGridTextColumn_Header_Property {
            get {
                return ResourceManager.GetString("Controls_ConnectionStringAdvancedOptionsWindow_DataGridTextColumn_Header_Property" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Controls_ConnectionStringAdvancedOptionsWindow_DataGridTextColumn_Header_Value {
            get {
                return ResourceManager.GetString("Controls_ConnectionStringAdvancedOptionsWindow_DataGridTextColumn_Header_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced....
        /// </summary>
        internal static string Controls_ConnectionStringEditWindow_Button_Content_Advanced {
            get {
                return ResourceManager.GetString("Controls_ConnectionStringEditWindow_Button_Content_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Controls_ConnectionStringEditWindow_Button_Content_Refresh {
            get {
                return ResourceManager.GetString("Controls_ConnectionStringEditWindow_Button_Content_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection.
        /// </summary>
        internal static string Controls_ConnectionStringEditWindow_Button_Content_TestConnection {
            get {
                return ResourceManager.GetString("Controls_ConnectionStringEditWindow_Button_Content_TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log on to the server.
        /// </summary>
        internal static string Controls_ConnectionStringEditWindow_GroupBox_Header_LogOnToTheServer {
            get {
                return ResourceManager.GetString("Controls_ConnectionStringEditWindow_GroupBox_Header_LogOnToTheServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database:.
        /// </summary>
        internal static string Controls_ConnectionStringEditWindow_Label_Content_Database {
            get {
                return ResourceManager.GetString("Controls_ConnectionStringEditWindow_Label_Content_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Controls_ConnectionStringEditWindow_Label_Content_Password {
            get {
                return ResourceManager.GetString("Controls_ConnectionStringEditWindow_Label_Content_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider:.
        /// </summary>
        internal static string Controls_ConnectionStringEditWindow_Label_Content_Provider {
            get {
                return ResourceManager.GetString("Controls_ConnectionStringEditWindow_Label_Content_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        internal static string Controls_ConnectionStringEditWindow_Label_Content_Server {
            get {
                return ResourceManager.GetString("Controls_ConnectionStringEditWindow_Label_Content_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string Controls_ConnectionStringEditWindow_Label_Content_UserName {
            get {
                return ResourceManager.GetString("Controls_ConnectionStringEditWindow_Label_Content_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SQL Server Authentication.
        /// </summary>
        internal static string Controls_ConnectionStringEditWindow_RadioButton_Content_UseSQLServerAuthentication {
            get {
                return ResourceManager.GetString("Controls_ConnectionStringEditWindow_RadioButton_Content_UseSQLServerAuthenticatio" +
                        "n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Windows Authentication.
        /// </summary>
        internal static string Controls_ConnectionStringEditWindow_RadioButton_Content_UseWindowsAuthentication {
            get {
                return ResourceManager.GetString("Controls_ConnectionStringEditWindow_RadioButton_Content_UseWindowsAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Controls_DatePicker_Button_Content_Clear {
            get {
                return ResourceManager.GetString("Controls_DatePicker_Button_Content_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Controls_DatePicker_Button_Content_Copy {
            get {
                return ResourceManager.GetString("Controls_DatePicker_Button_Content_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Controls_DatePicker_Button_Content_Paste {
            get {
                return ResourceManager.GetString("Controls_DatePicker_Button_Content_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select date.
        /// </summary>
        internal static string Controls_DatePicker_Button_Content_SelectDate {
            get {
                return ResourceManager.GetString("Controls_DatePicker_Button_Content_SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Controls_DatePicker_Button_Content_Today {
            get {
                return ResourceManager.GetString("Controls_DatePicker_Button_Content_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        internal static string Controls_DatePicker_ToggleButton_Content_DayAbbreviation {
            get {
                return ResourceManager.GetString("Controls_DatePicker_ToggleButton_Content_DayAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string Controls_DatePicker_ToggleButton_Content_MonthAbbreviation {
            get {
                return ResourceManager.GetString("Controls_DatePicker_ToggleButton_Content_MonthAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        internal static string Controls_DatePicker_ToggleButton_Content_YearAbbreviation {
            get {
                return ResourceManager.GetString("Controls_DatePicker_ToggleButton_Content_YearAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Controls_DatePickerControl_Button_Content_Clear {
            get {
                return ResourceManager.GetString("Controls_DatePickerControl_Button_Content_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Controls_DatePickerControl_Button_Content_Copy {
            get {
                return ResourceManager.GetString("Controls_DatePickerControl_Button_Content_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Controls_DatePickerControl_Button_Content_Paste {
            get {
                return ResourceManager.GetString("Controls_DatePickerControl_Button_Content_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select date.
        /// </summary>
        internal static string Controls_DatePickerControl_Button_Content_SelectDate {
            get {
                return ResourceManager.GetString("Controls_DatePickerControl_Button_Content_SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Controls_DatePickerControl_Button_Content_Today {
            get {
                return ResourceManager.GetString("Controls_DatePickerControl_Button_Content_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        internal static string Controls_DatePickerControl_ToggleButton_Content_DayAbbreviation {
            get {
                return ResourceManager.GetString("Controls_DatePickerControl_ToggleButton_Content_DayAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string Controls_DatePickerControl_ToggleButton_Content_MonthAbbreviation {
            get {
                return ResourceManager.GetString("Controls_DatePickerControl_ToggleButton_Content_MonthAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        internal static string Controls_DatePickerControl_ToggleButton_Content_YearAbbreviation {
            get {
                return ResourceManager.GetString("Controls_DatePickerControl_ToggleButton_Content_YearAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust duration.
        /// </summary>
        internal static string Controls_DateRangePicker_Adj_Duration {
            get {
                return ResourceManager.GetString("Controls_DateRangePicker_Adj_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust end time.
        /// </summary>
        internal static string Controls_DateRangePicker_Adj_End_Time {
            get {
                return ResourceManager.GetString("Controls_DateRangePicker_Adj_End_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time adjustment strategy:.
        /// </summary>
        internal static string Controls_DateRangePicker_Adj_Strategy_Lbl {
            get {
                return ResourceManager.GetString("Controls_DateRangePicker_Adj_Strategy_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string Controls_DateRangePicker_Custom {
            get {
                return ResourceManager.GetString("Controls_DateRangePicker_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration can&apos;t be less than zero.
        /// </summary>
        internal static string Controls_DateRangePicker_Duration_NotLess_Zero_Validation {
            get {
                return ResourceManager.GetString("Controls_DateRangePicker_Duration_NotLess_Zero_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End:.
        /// </summary>
        internal static string Controls_DateRangePicker_End_Lbl {
            get {
                return ResourceManager.GetString("Controls_DateRangePicker_End_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date can&apos;t be less than Start date.
        /// </summary>
        internal static string Controls_DateRangePicker_EndDate_NotLess_StartDate_Validation {
            get {
                return ResourceManager.GetString("Controls_DateRangePicker_EndDate_NotLess_StartDate_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last month.
        /// </summary>
        internal static string Controls_DateRangePicker_LastMonth {
            get {
                return ResourceManager.GetString("Controls_DateRangePicker_LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last week.
        /// </summary>
        internal static string Controls_DateRangePicker_LastWeek {
            get {
                return ResourceManager.GetString("Controls_DateRangePicker_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start:.
        /// </summary>
        internal static string Controls_DateRangePicker_Start_Lbl {
            get {
                return ResourceManager.GetString("Controls_DateRangePicker_Start_Lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This month.
        /// </summary>
        internal static string Controls_DateRangePicker_ThisMonth {
            get {
                return ResourceManager.GetString("Controls_DateRangePicker_ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This week.
        /// </summary>
        internal static string Controls_DateRangePicker_ThisWeek {
            get {
                return ResourceManager.GetString("Controls_DateRangePicker_ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Controls_DateRangePicker_Today {
            get {
                return ResourceManager.GetString("Controls_DateRangePicker_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string Controls_DateRangePicker_Yesterday {
            get {
                return ResourceManager.GetString("Controls_DateRangePicker_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Controls_DateTimePicker_Button_Content_Clear {
            get {
                return ResourceManager.GetString("Controls_DateTimePicker_Button_Content_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Controls_DateTimePicker_Button_Content_Copy {
            get {
                return ResourceManager.GetString("Controls_DateTimePicker_Button_Content_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        internal static string Controls_DateTimePicker_Button_Content_Now {
            get {
                return ResourceManager.GetString("Controls_DateTimePicker_Button_Content_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Controls_DateTimePicker_Button_Content_Paste {
            get {
                return ResourceManager.GetString("Controls_DateTimePicker_Button_Content_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select date.
        /// </summary>
        internal static string Controls_DateTimePicker_Button_Content_SelectDate {
            get {
                return ResourceManager.GetString("Controls_DateTimePicker_Button_Content_SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select time.
        /// </summary>
        internal static string Controls_DateTimePicker_Button_Content_SelectTime {
            get {
                return ResourceManager.GetString("Controls_DateTimePicker_Button_Content_SelectTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Controls_DateTimePicker_Button_Content_Today {
            get {
                return ResourceManager.GetString("Controls_DateTimePicker_Button_Content_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t.
        /// </summary>
        internal static string Controls_DateTimePicker_ToggleButton_Content_AmPmAbbreviation {
            get {
                return ResourceManager.GetString("Controls_DateTimePicker_ToggleButton_Content_AmPmAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        internal static string Controls_DateTimePicker_ToggleButton_Content_DayAbbreviation {
            get {
                return ResourceManager.GetString("Controls_DateTimePicker_ToggleButton_Content_DayAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        internal static string Controls_DateTimePicker_ToggleButton_Content_HourAbbreviation {
            get {
                return ResourceManager.GetString("Controls_DateTimePicker_ToggleButton_Content_HourAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string Controls_DateTimePicker_ToggleButton_Content_MinuteAbbreviation {
            get {
                return ResourceManager.GetString("Controls_DateTimePicker_ToggleButton_Content_MinuteAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string Controls_DateTimePicker_ToggleButton_Content_MonthAbbreviation {
            get {
                return ResourceManager.GetString("Controls_DateTimePicker_ToggleButton_Content_MonthAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string Controls_DateTimePicker_ToggleButton_Content_SecondAbbreviation {
            get {
                return ResourceManager.GetString("Controls_DateTimePicker_ToggleButton_Content_SecondAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        internal static string Controls_DateTimePicker_ToggleButton_Content_YearAbbreviation {
            get {
                return ResourceManager.GetString("Controls_DateTimePicker_ToggleButton_Content_YearAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Controls_DateTimePickerControl_Button_Content_Clear {
            get {
                return ResourceManager.GetString("Controls_DateTimePickerControl_Button_Content_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Controls_DateTimePickerControl_Button_Content_Copy {
            get {
                return ResourceManager.GetString("Controls_DateTimePickerControl_Button_Content_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        internal static string Controls_DateTimePickerControl_Button_Content_Now {
            get {
                return ResourceManager.GetString("Controls_DateTimePickerControl_Button_Content_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Controls_DateTimePickerControl_Button_Content_Paste {
            get {
                return ResourceManager.GetString("Controls_DateTimePickerControl_Button_Content_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select date.
        /// </summary>
        internal static string Controls_DateTimePickerControl_Button_Content_SelectDate {
            get {
                return ResourceManager.GetString("Controls_DateTimePickerControl_Button_Content_SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Controls_DateTimePickerControl_Button_Content_Today {
            get {
                return ResourceManager.GetString("Controls_DateTimePickerControl_Button_Content_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t.
        /// </summary>
        internal static string Controls_DateTimePickerControl_ToggleButton_Content_AmPmAbbreviation {
            get {
                return ResourceManager.GetString("Controls_DateTimePickerControl_ToggleButton_Content_AmPmAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        internal static string Controls_DateTimePickerControl_ToggleButton_Content_DayAbbreviation {
            get {
                return ResourceManager.GetString("Controls_DateTimePickerControl_ToggleButton_Content_DayAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        internal static string Controls_DateTimePickerControl_ToggleButton_Content_HourAbbreviation {
            get {
                return ResourceManager.GetString("Controls_DateTimePickerControl_ToggleButton_Content_HourAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string Controls_DateTimePickerControl_ToggleButton_Content_MinuteAbbreviation {
            get {
                return ResourceManager.GetString("Controls_DateTimePickerControl_ToggleButton_Content_MinuteAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string Controls_DateTimePickerControl_ToggleButton_Content_MonthAbbreviation {
            get {
                return ResourceManager.GetString("Controls_DateTimePickerControl_ToggleButton_Content_MonthAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string Controls_DateTimePickerControl_ToggleButton_Content_SecondAbbreviation {
            get {
                return ResourceManager.GetString("Controls_DateTimePickerControl_ToggleButton_Content_SecondAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        internal static string Controls_DateTimePickerControl_ToggleButton_Content_YearAbbreviation {
            get {
                return ResourceManager.GetString("Controls_DateTimePickerControl_ToggleButton_Content_YearAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Controls_DbConnectionProviderListWindow_Button_Content_Refresh {
            get {
                return ResourceManager.GetString("Controls_DbConnectionProviderListWindow_Button_Content_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change....
        /// </summary>
        internal static string Controls_DbProviderControl_Button_Content_Change {
            get {
                return ResourceManager.GetString("Controls_DbProviderControl_Button_Content_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change....
        /// </summary>
        internal static string Controls_DbProviderPicker_Button_Content_Change {
            get {
                return ResourceManager.GetString("Controls_DbProviderPicker_Button_Content_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string Controls_LogMessageCategoryToggleButton_Text_Debug {
            get {
                return ResourceManager.GetString("Controls_LogMessageCategoryToggleButton_Text_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Controls_LogMessageCategoryToggleButton_Text_Error {
            get {
                return ResourceManager.GetString("Controls_LogMessageCategoryToggleButton_Text_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Controls_LogMessageCategoryToggleButton_Text_Info {
            get {
                return ResourceManager.GetString("Controls_LogMessageCategoryToggleButton_Text_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Controls_LogMessageCategoryToggleButton_Text_Warning {
            get {
                return ResourceManager.GetString("Controls_LogMessageCategoryToggleButton_Text_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Controls_LogViewer_Add {
            get {
                return ResourceManager.GetString("Controls_LogViewer_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string Controls_LogViewer_AreYouSure {
            get {
                return ResourceManager.GetString("Controls_LogViewer_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Controls_LogViewer_Edit {
            get {
                return ResourceManager.GetString("Controls_LogViewer_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Controls_LogViewer_LogFilterEditor_Action {
            get {
                return ResourceManager.GetString("Controls_LogViewer_LogFilterEditor_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression Type.
        /// </summary>
        internal static string Controls_LogViewer_LogFilterEditor_ExpressionType {
            get {
                return ResourceManager.GetString("Controls_LogViewer_LogFilterEditor_ExpressionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression Value.
        /// </summary>
        internal static string Controls_LogViewer_LogFilterEditor_ExpressionValue {
            get {
                return ResourceManager.GetString("Controls_LogViewer_LogFilterEditor_ExpressionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression value is required.
        /// </summary>
        internal static string Controls_LogViewer_LogFilterEditor_ExpressionValueIsRequired {
            get {
                return ResourceManager.GetString("Controls_LogViewer_LogFilterEditor_ExpressionValueIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter name.
        /// </summary>
        internal static string Controls_LogViewer_LogFilterEditor_FilterName {
            get {
                return ResourceManager.GetString("Controls_LogViewer_LogFilterEditor_FilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        internal static string Controls_LogViewer_LogFilterEditor_NameIsRequired {
            get {
                return ResourceManager.GetString("Controls_LogViewer_LogFilterEditor_NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string Controls_LogViewer_LogFilterEditor_Target {
            get {
                return ResourceManager.GetString("Controls_LogViewer_LogFilterEditor_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        internal static string Controls_LogViewer_LogFilterGroupEditor_GroupName {
            get {
                return ResourceManager.GetString("Controls_LogViewer_LogFilterGroupEditor_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Filters.
        /// </summary>
        internal static string Controls_LogViewer_LogFilterGroupEditor_LogFilters {
            get {
                return ResourceManager.GetString("Controls_LogViewer_LogFilterGroupEditor_LogFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Name&apos; for the LogFilterGroup is required.
        /// </summary>
        internal static string Controls_LogViewer_LogFilterGroupEditor_NameForTheLogFilterGroupIsRequired {
            get {
                return ResourceManager.GetString("Controls_LogViewer_LogFilterGroupEditor_NameForTheLogFilterGroupIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Filter Group Editor.
        /// </summary>
        internal static string Controls_LogViewer_LogFilterGroupEditor_Title {
            get {
                return ResourceManager.GetString("Controls_LogViewer_LogFilterGroupEditor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Controls_LogViewer_Remove {
            get {
                return ResourceManager.GetString("Controls_LogViewer_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select type name --.
        /// </summary>
        internal static string Controls_LogViewer_SelectTypeName {
            get {
                return ResourceManager.GetString("Controls_LogViewer_SelectTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        internal static string Controls_OpenFolder {
            get {
                return ResourceManager.GetString("Controls_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Controls_TimePickerControl_Button_Content_Clear {
            get {
                return ResourceManager.GetString("Controls_TimePickerControl_Button_Content_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Controls_TimePickerControl_Button_Content_Copy {
            get {
                return ResourceManager.GetString("Controls_TimePickerControl_Button_Content_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        internal static string Controls_TimePickerControl_Button_Content_Now {
            get {
                return ResourceManager.GetString("Controls_TimePickerControl_Button_Content_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Controls_TimePickerControl_Button_Content_Paste {
            get {
                return ResourceManager.GetString("Controls_TimePickerControl_Button_Content_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select time.
        /// </summary>
        internal static string Controls_TimePickerControl_Button_Content_SelectTime {
            get {
                return ResourceManager.GetString("Controls_TimePickerControl_Button_Content_SelectTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        internal static string Controls_TimeSpanControl_TextBlock_Text_DaysAbbreviation {
            get {
                return ResourceManager.GetString("Controls_TimeSpanControl_TextBlock_Text_DaysAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        internal static string Controls_TimeSpanControl_TextBlock_Text_HoursAbbreviation {
            get {
                return ResourceManager.GetString("Controls_TimeSpanControl_TextBlock_Text_HoursAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string Controls_TimeSpanControl_TextBlock_Text_MinutesAbbreviation {
            get {
                return ResourceManager.GetString("Controls_TimeSpanControl_TextBlock_Text_MinutesAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string Controls_TimeSpanControl_TextBlock_Text_SecondsAbbreviation {
            get {
                return ResourceManager.GetString("Controls_TimeSpanControl_TextBlock_Text_SecondsAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        internal static string Controls_TimeSpanPicker_TextBlock_Text_DaysAbbreviation {
            get {
                return ResourceManager.GetString("Controls_TimeSpanPicker_TextBlock_Text_DaysAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        internal static string Controls_TimeSpanPicker_TextBlock_Text_HoursAbbreviation {
            get {
                return ResourceManager.GetString("Controls_TimeSpanPicker_TextBlock_Text_HoursAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string Controls_TimeSpanPicker_TextBlock_Text_MinutesAbbreviation {
            get {
                return ResourceManager.GetString("Controls_TimeSpanPicker_TextBlock_Text_MinutesAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string Controls_TimeSpanPicker_TextBlock_Text_SecondsAbbreviation {
            get {
                return ResourceManager.GetString("Controls_TimeSpanPicker_TextBlock_Text_SecondsAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string Controls_TimeSpanPickerGeneric_TextBlock_Text_Days {
            get {
                return ResourceManager.GetString("Controls_TimeSpanPickerGeneric_TextBlock_Text_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string Controls_TimeSpanPickerGeneric_TextBlock_Text_Hours {
            get {
                return ResourceManager.GetString("Controls_TimeSpanPickerGeneric_TextBlock_Text_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string Controls_TimeSpanPickerGeneric_TextBlock_Text_Minutes {
            get {
                return ResourceManager.GetString("Controls_TimeSpanPickerGeneric_TextBlock_Text_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        internal static string Controls_TimeSpanPickerGeneric_TextBlock_Text_Total {
            get {
                return ResourceManager.GetString("Controls_TimeSpanPickerGeneric_TextBlock_Text_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all.
        /// </summary>
        internal static string Controls_ValidationContextControl_CollapseAll {
            get {
                return ResourceManager.GetString("Controls_ValidationContextControl_CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Controls_ValidationContextControl_Copy {
            get {
                return ResourceManager.GetString("Controls_ValidationContextControl_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        internal static string Controls_ValidationContextControl_Errors {
            get {
                return ResourceManager.GetString("Controls_ValidationContextControl_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all.
        /// </summary>
        internal static string Controls_ValidationContextControl_ExpandAll {
            get {
                return ResourceManager.GetString("Controls_ValidationContextControl_ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Controls_ValidationContextControl_Filter {
            get {
                return ResourceManager.GetString("Controls_ValidationContextControl_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        internal static string Controls_ValidationContextControl_Misc {
            get {
                return ResourceManager.GetString("Controls_ValidationContextControl_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Controls_ValidationContextControl_Open {
            get {
                return ResourceManager.GetString("Controls_ValidationContextControl_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        internal static string Controls_ValidationContextControl_Warnings {
            get {
                return ResourceManager.GetString("Controls_ValidationContextControl_Warnings", resourceCulture);
            }
        }
    }
}
