//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("WildGums")]
[assembly: AssemblyVersion("5.4.0")]
[assembly: AssemblyFileVersion("5.4.0")]
[assembly: AssemblyInformationalVersion("5.4.0-alpha.107")]
[assembly: AssemblyCopyright("Copyright © WildGums 2014 - 2025")]

