<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
    <AssemblyName>Orc.Controls.Example</AssemblyName>
    <RootNamespace>Orc.Controls.Example</RootNamespace>
    <DefaultLanguage>en-US</DefaultLanguage>
    <SonarQubeExclude>true</SonarQubeExclude>
  </PropertyGroup>

  <PropertyGroup>
    <UseWpf>true</UseWpf>
    <OutputType>WinExe</OutputType>
    <StartupObject />
    <NoWarn>$(NoWarn);SA1652</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Catel.Fody" Version="7.1.0-alpha0016" PrivateAssets="all" />
    <PackageReference Include="Catel.SourceGenerators" Version="7.1.0-alpha0083" PrivateAssets="all" />
    <PackageReference Include="Fody" Version="6.9.3" PrivateAssets="all">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.*" />
    <PackageReference Include="Orchestra.Core" Version="8.0.0-alpha0321" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Orc.Controls\Orc.Controls.csproj" />
  </ItemGroup>

  <Import Project="$(MSBuildProjectDirectory)\..\Directory.Build.shared.explicit.props" Condition="Exists('$(MSBuildProjectDirectory)\..\Directory.Build.shared.explicit.props')" />
</Project>
